### ISSUE TITLE
SSL certificate issue for bmdb.jpl.nasa.gov

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/Infrastructure#6]
On the host tumor.jpl.nasa.gov, this command gives an SSL CERTIFICATE_VERIFY_FAILED:

```console
tumor 249 $ hostname
tumor.jpl.nasa.gov
tumor 250 $ date -u
Sat Aug  8 13:27:18 UTC 2020
tumor 251 $ /usr/local/python-2.7.10/bin/python2.7 -c 'import urllib2; urllib2.urlopen("https://bmdb.jpl.nasa.gov/")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
tumor 252 $ echo \U+01F44E
👎
```

But this command  works:

```console
tumor 253 $ /usr/local/python-2.7.10/bin/python2.7 -c 'import urllib2; urllib2.urlopen("https://edrn.jpl.nasa.gov/")'
tumor 254 $ echo \U+01F44D
👍
```

Can we make bmdb.jpl.nasa.gov's SSL certificate behave like edrn.jpl.nasa.gov's?

(Reported via email to `sa@list.jpl.nasa.gov` in Message-ID: `2fe1c102-9b5b-fed7-e14d-f801b3afd439@jpl.nasa.gov`)

**Comment by nutjob4life** [comment]
Fixed by Rojeh on 2020-08-10 in Message-ID: `7DAD14E2-4611-4224-B840-138F1EFB1737@jpl.nasa.gov`.
