### ISSUE TITLE
Directory is down

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/Infrastructure#8]
## ✋ What's Down?

`ldaps://edrn-ds.jpl.nasa.gov` is down

## 📜 How Do You Usually Access It?

Usually with an LDAP client.

## 🔎 Expected Behavior

Answers to LDAP queries; instead, port 636 answers but nothing further.

## 🖼 Screenshots

```console
[16:39:00] ERROR [org.apache.directory.server.wrapper.ApacheDsTanukiWrapper] - Failed to start the service.
java.lang.RuntimeException: the working directory /usr/local/apacheds-instances/edrn-ds-fresh/run has been locked by another directory service.
        at org.apache.directory.server.core.DefaultDirectoryService.lockWorkDir(DefaultDirectoryService.java:2412)
        at org.apache.directory.server.core.DefaultDirectoryService.startup(DefaultDirectoryService.java:1250)
        at org.apache.directory.server.ApacheDsService.initDirectoryService(ApacheDsService.java:363)
        at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:196)
        at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:152)
        at org.apache.directory.server.wrapper.ApacheDsTanukiWrapper.start(ApacheDsTanukiWrapper.java:175)
        at org.tanukisoftware.wrapper.WrapperManager$12.run(WrapperManager.java:2788)
```

## 🕵️‍♀️ Extra Details

Alerted [📧 system admins](mailto:sa@list.jpl.nasa.gov) in email Message-ID: `15fa740d-c2ef-abe9-ec0a-b3a49d9d6e67@jpl.nasa.gov`.

**Comment by nutjob4life** [comment]
Fixed by [📧Andrew Zimdars](mailto:andrew.t.zimdars@jpl.nasa.gov), in email Message-ID: `942e01435fed452382486bcd95fb47f5@jpl.nasa.gov`.
